import { useState } from 'react'
import './App.css'

const quotes = [
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "So many books, so little time.", author: "Frank Zappa" },
  { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.", author: "Bernard M. Baruch" },
  { text: "You've gotta dance like there's nobody watching, love like you'll never be hurt, sing like there's nobody listening, and live like it's heaven on earth.", author: "William W. Purkey" },
  { text: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard" },
  { text: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "Insanity is doing the same thing, over and over again, but expecting different results.", author: "Narcotics Anonymous" },
  { text: "It is better to be hated for what you are than to be loved for what you are not.", author: "Andre Gide" },
  { text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.", author: "H. Jackson Brown Jr." },
  { text: "All that is gold does not glitter, not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.", author: "Jane Austen" },
  { text: "It is our choices, Harry, that show what we truly are, far more than our abilities.", author: "J.K. Rowling" },
  { text: "It does not do to dwell on dreams and forget to live.", author: "J.K. Rowling" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", author: "William Shakespeare" },
  { text: "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", author: "Neil Gaiman" },
  { text: "It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.", author: "Maurice Switzer" },
  { text: "I love you without knowing how, or when, or from where. I love you simply, without problems or pride.", author: "Pablo Neruda" },
  { text: "I may not have gone where I intended to go, but I think I have ended up where I needed to be.", author: "Douglas Adams" },
  { text: "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.", author: "Groucho Marx" },
  { text: "I solemnly swear that I am up to no good.", author: "J.K. Rowling" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
  { text: "A reader lives a thousand lives before he dies. The man who never reads lives only one.", author: "George R.R. Martin" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
  { text: "I love deadlines. I love the whooshing noise they make as they go by.", author: "Douglas Adams" },
  { text: "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", author: "J.K. Rowling" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "If you only read the books that everyone else is reading, you can only think what everyone else is thinking.", author: "Haruki Murakami" },
  { text: "There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.", author: "Sarah Dessen" },
  { text: "Love is that condition in which the happiness of another person is essential to your own.", author: "Robert A. Heinlein" },
  { text: "Never trust anyone who has not brought a book with them.", author: "Lemony Snicket" },
  { text: "We read to know we're not alone.", author: "William Nicholson" },
  { text: "Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?", author: "J.K. Rowling" },
  { text: "Today you are You, that is truer than true. There is no one alive who is Youer than You.", author: "Dr. Seuss" },
  { text: "To the well-organized mind, death is but the next great adventure.", author: "J.K. Rowling" },
  { text: "Whenever I feel the need to exercise, I lie down until it goes away.", author: "Jerome K. Jerome" },
  { text: "Sometimes people are beautiful. Not in looks. Not in what they say. Just in what they are.", author: "Markus Zusak" },
  { text: "Love looks not with the eyes, but with the mind; And therefore is wing'd Cupid painted blind.", author: "William Shakespeare" },
  { text: "You don't get to choose if you get hurt in this world... but you do have some say in who hurts you. I like my choices.", author: "John Green" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { text: "The story so far: In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.", author: "Douglas Adams" },
  { text: "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.", author: "Jane Austen" },
  { text: "Love is like the wind, you can't see it but you can feel it.", author: "Nicholas Sparks" },
  { text: "You don't love someone because they're perfect, you love them in spite of the fact that they're not.", author: "Jodi Picoult" },
  { text: "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.", author: "A.A. Milne" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J.R.R. Tolkien" },
  { text: "It matters not what someone is born, but what they grow to be.", author: "J.K. Rowling" },
  { text: "We're all a little weird. And life is a little weird. And when we find someone whose weirdness is compatible with ours, we join up with them and fall into mutually satisfying weirdness—and call it love—true love.", author: "Robert Fulghum" },
  { text: "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.", author: "Terry Pratchett" },
  { text: "Reality continues to ruin my life.", author: "Bill Watterson" },
  { text: "Some infinities are bigger than other infinities.", author: "John Green" },
  { text: "You don't have a soul, Doctor. You are a soul. You have a body, temporarily.", author: "Walter M. Miller Jr." },
  { text: "One must always be careful of books, and what is inside them, for words have the power to change us.", author: "Cassandra Clare" },
  { text: "Time you enjoy wasting is not wasted time.", author: "Marthe Troly-Curtin" },
  { text: "Things change. And friends leave. Life doesn't stop for anybody.", author: "Stephen Chbosky" },
  { text: "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book!", author: "Jane Austen" },
  { text: "To love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken.", author: "C.S. Lewis" },
  { text: "The books that the world calls immoral are books that show the world its own shame.", author: "Oscar Wilde" },
  { text: "And, when you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho" },
  { text: "The only way out of the labyrinth of suffering is to forgive.", author: "John Green" },
  { text: "Piglet sidled up to Pooh from behind. Pooh! he whispered. Yes, Piglet? Nothing, said Piglet, taking Pooh's paw. I just wanted to be sure of you.", author: "A.A. Milne" },
  { text: "Do not pity the dead, Harry. Pity the living, and, above all those who live without love.", author: "J.K. Rowling" },
  { text: "After all this time? Always.", author: "J.K. Rowling" },
  { text: "You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.", author: "Harper Lee" },
  { text: "The marks humans leave are too often scars.", author: "John Green" },
  { text: "We are what we pretend to be, so we must be careful about what we pretend to be.", author: "Kurt Vonnegut" },
  { text: "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.", author: "Jane Austen" },
  { text: "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.", author: "Marianne Williamson" },
  { text: "Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.", author: "Suzanne Collins" },
  { text: "Books are a uniquely portable magic.", author: "Stephen King" },
  { text: "And in that moment, I swear we were infinite.", author: "Stephen Chbosky" },
  { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
  { text: "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.", author: "Jimi Hendrix" },
  { text: "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration.", author: "Frank Herbert" },
  { text: "So it's not gonna be easy. It's going to be really hard; we're gonna have to work at this everyday, but I want to do that because I want you.", author: "Nicholas Sparks" },
  { text: "A mind needs books as a sword needs a whetstone, if it is to keep its edge.", author: "George R.R. Martin" },
  { text: "Memories warm you up from the inside. But they also tear you apart.", author: "Haruki Murakami" },
  { text: "We believe in ordinary acts of bravery, in the courage that drives one person to stand up for another.", author: "Veronica Roth" },
  { text: "There is nothing better than a friend, unless it is a friend with chocolate.", author: "Linda Grayson" },
  { text: "The truth. It is a beautiful and terrible thing, and should therefore be treated with great caution.", author: "J.K. Rowling" },
  { text: "Never tell the truth to people who are not worthy of it.", author: "Mark Twain" },
  { text: "I love you as certain dark things are to be loved, in secret, between the shadow and the soul.", author: "Pablo Neruda" },
  { text: "Perhaps one did not want to be loved so much as to be understood.", author: "George Orwell" },
  { text: "It's the possibility of having a dream come true that makes life interesting.", author: "Paulo Coelho" },
  { text: "Tis better to have loved and lost than never to have loved at all.", author: "Alfred Lord Tennyson" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.", author: "William Shakespeare" },
  { text: "What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it.", author: "Maya Angelou" },
  { text: "Happiness in intelligent people is the rarest thing I know.", author: "Ernest Hemingway" },
  { text: "He's not perfect. You aren't either, and the two of you will never be perfect. But if he can make you laugh at least once, causes you to think twice, and if he admits to being human and making mistakes, hold onto him and give him the most you can.", author: "Bob Marley" },
  { text: "A day without laughter is a day wasted.", author: "Nicolas Chamfort" },
  { text: "You can never be overdressed or overeducated.", author: "Oscar Wilde" },
  { text: "I became insane, with long intervals of horrible sanity.", author: "Edgar Allan Poe" },
  { text: "It is one of the blessings of old friends that you can afford to be stupid with them.", author: "Ralph Waldo Emerson" },
  { text: "The one you love and the one who loves you are never, ever the same person.", author: "Chuck Palahniuk" },
  { text: "You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.", author: "Albert Camus" },
  { text: "When adults say, Teenagers think they are invincible with that sly, stupid smile on their faces, they don't know how right they are.", author: "John Green" },
  { text: "Books are the quietest and most constant of friends; they are the most accessible and wisest of counselors, and the most patient of teachers.", author: "Charles W. Eliot" },
  { text: "Music expresses that which cannot be put into words and that which cannot remain silent.", author: "Victor Hugo" },
  { text: "I am no bird; and no net ensnares me: I am a free human being with an independent will.", author: "Charlotte Brontë" },
  { text: "Have you ever noticed how 'What the hell' is always the right decision to make?", author: "Terry Johnson" },
  { text: "Those who don't believe in magic will never find it.", author: "Roald Dahl" },
  { text: "An eye for an eye will only make the whole world blind.", author: "Mahatma Gandhi" },
  { text: "Until I feared I would lose it, I never loved to read. One does not love breathing.", author: "Harper Lee" },
  { text: "When we love, we always strive to become better than we are. When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho" },
  { text: "I speak to everyone in the same way, whether he is the garbage man or the president of the university.", author: "Albert Einstein" },
  { text: "With great power... comes great need to take a nap. Wake me up later.", author: "Rick Riordan" },
  { text: "A children's story that can only be enjoyed by children is not a good children's story in the slightest.", author: "C.S. Lewis" },
  { text: "I would rather walk with a friend in the dark, than alone in the light.", author: "Helen Keller" },
  { text: "So I walked back to my room and collapsed on the bottom bunk, thinking that if people were rain, I was drizzle and she was a hurricane.", author: "John Green" },
  { text: "A great book should leave you with many experiences, and slightly exhausted at the end. You live several lives while reading.", author: "William Styron" },
  { text: "Fate is like a strange, unpopular restaurant filled with odd little waiters who bring you things you never asked for and don't always like.", author: "Lemony Snicket" },
  { text: "If you don't have time to read, you don't have the time (or the tools) to write. Simple as that.", author: "Stephen King" },
  { text: "Creativity is knowing how to hide your sources.", author: "C.E.M. Joad" },
  { text: "He's more myself than I am. Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.", author: "Terry Pratchett" },
  { text: "I no longer believed in the idea of soul mates, or love at first sight. But I was beginning to believe that a very few times in your life, if you were lucky, you might meet someone who was exactly right for you.", author: "Lisa Kleypas" },
  { text: "Never forget what you are, for surely the world will not. Make it your strength. Then it can never be your weakness.", author: "George R.R. Martin" },
  { text: "So we beat on, boats against the current, borne back ceaselessly into the past.", author: "F. Scott Fitzgerald" },
  { text: "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", author: "Virginia Woolf" },
  { text: "One is loved because one is loved. No reason is needed for loving.", author: "Paulo Coelho" },
  { text: "Well-behaved women seldom make history.", author: "Laurel Thatcher Ulrich" },
  { text: "Life is an awful, ugly place to not have a best friend.", author: "Sarah Dessen" },
  { text: "I don't know half of you half as well as I should like; and I like less than half of you half as well as you deserve.", author: "J.R.R. Tolkien" },
  { text: "In vain have I struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you.", author: "Jane Austen" },
  { text: "We're all human, aren't we? Every human life is worth the same, and worth saving.", author: "J.K. Rowling" },
  { text: "Two roads diverged in a wood, and I— I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },
  { text: "The world is not a wish-granting factory.", author: "John Green" },
  { text: "Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage.", author: "Rainer Maria Rilke" },
  { text: "There's nothing like deep breaths after laughing that hard. Nothing in the world like a sore stomach for the right reasons.", author: "Stephen Chbosky" },
  { text: "I am not pretty. I am not beautiful. I am as radiant as the sun.", author: "Suzanne Collins" },
  { text: "Above all, don't lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him, or around him, and so loses all respect for himself and for others.", author: "Fyodor Dostoevsky" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" }
]

function App() {
  const [quote, setQuote] = useState({
    text: "Click the button to get inspired.",
    author: ""
  })
  const [fadeKey, setFadeKey] = useState(0)

  const handleQuote = () => {
    const random = quotes[Math.floor(Math.random() * quotes.length)]
    setQuote(random)
    setFadeKey(prev => prev + 1)
  }

  return (
    <div className="quote-box">
      <div className="quote-text fade-in" key={fadeKey}>
        {quote.author ? `"${quote.text}"` : quote.text}
      </div>
      <div className="quote-author">
        {quote.author ? `— ${quote.author}` : ""}
      </div>
      <button className="quote-btn" onClick={handleQuote}>
        QUOTE
      </button>
    </div>
  )
}

export default App
